apiVersion: resilience.io/v1
kind: DRPolicy
metadata:
  name: ecommerce-dr-policy
  namespace: default
spec:
  targetNamespace: "prod-e-commerce"
  healthCheckEndpoint: "http://172.18.0.5:31698"
  failureThresholdSeconds: 10
  veleroBackupName: "e-commerce-golden-backup"
  chaosEnabled: true
